version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: messenger_postgres
    environment:
      POSTGRES_DB: messenger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - messenger_network

  redis:
    image: redis:7-alpine
    container_name: messenger_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - messenger_network

  app:
    build: .
    container_name: messenger_app
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=messenger
      - DB_SSL_MODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_PORT=8080
      - JWT_SECRET=your-super-secret-key-change-this-in-production
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - messenger_network

volumes:
  postgres_data:
  redis_data:

networks:
  messenger_network:
    driver: bridge